const data = {
  products: [
    {
      _id: '1',
      name: 'Adidas Cricket Bat',
      catergory: 'Cricker Bats',
      image: '/images/d1.jpg',
      price: 200,
      countInStock: 10,
      brand: 'Adidas',
      rating: 5,
      numReviews: 20,
      description: 'High quality cricket bat',
    },
    {
      _id: '2',
      name: 'MRF Cricket Bat',
      catergory: 'Cricker Bats',
      image: '/images/d2.jpg',
      price: 330,
      countInStock: 20,
      brand: 'MRF',
      rating: 5,
      numReviews: 25,
      description: 'High quality cricket bat',
    },
    {
      _id: '3',
      name: 'PUMA Cricket Bat',
      catergory: 'Cricker Bats',
      image: '/images/d3.jpg',
      price: 320,
      countInStock: 25,
      brand: 'PUMA',
      rating: 5,
      numReviews: 19,
      description: 'High quality cricket bat',
    },
    {
      _id: '4',
      name: 'Gray-Nicolas Cricket Bat',
      catergory: 'Cricker Bats',
      image: '/images/d4.jpg',
      price: 280,
      countInStock: 12,
      brand: 'Gray-Nicolas',
      rating: 5,
      numReviews: 10,
      description: 'High quality cricket bat',
    },
    {
      _id: '5',
      name: 'Newbury Cricket Bat',
      catergory: 'Cricker Bats',
      image: '/images/d5.jpg',
      price: 250,
      countInStock: 18,
      brand: 'Newbury',
      rating: 5,
      numReviews: 14,
      description: 'High quality cricket bat',
    },
    {
      _id: '6',
      name: 'Kookabura Cricket Bat',
      catergory: 'Cricker Bats',
      image: '/images/d6.jpg',
      price: 300,
      countInStock: 16,
      brand: 'Kookabura',
      rating: 5,
      numReviews: 15,
      description: 'High quality cricket bat',
    },
    {
      _id: '7',
      name: 'CA Cricket Bat',
      catergory: 'Cricker Bats',
      image: '/images/d7.jpg',
      price: 320,
      countInStock: 10,
      brand: 'CA ',
      rating: 5,
      numReviews: 20,
      description: 'High quality cricket bat',
    },
    {
      _id: '8',
      name: 'Insignia County Hunts Cricket Bat',
      catergory: 'Cricker Bats',
      image: '/images/d8.jpg',
      price: 280,
      countInStock: 11,
      brand: 'Insignia County Hunts ',
      rating: 4,
      numReviews: 22,
      description: 'High quality cricket bat',
    },
    {
      _id: '9',
      name: 'Chase Cricket Bat',
      catergory: 'Cricker Bats',
      image: '/images/d9.jpg',
      price: 220,
      countInStock: 0,
      brand: 'Chase ',
      rating: 4,
      numReviews: 10,
      description: 'High quality cricket bat',
    },
    {
      _id: '10',
      name: 'SS TON Cricket Bat',
      catergory: 'Cricker Bats',
      image: '/images/d10.jpg',
      price: 250,
      countInStock: 14,
      brand: 'SS TON ',
      rating: 5,
      numReviews: 11,
      description: 'High quality cricket bat',
    },
    {
      _id: '11',
      name: 'Spartan Cricket Bat',
      catergory: 'Cricker Bats',
      image: '/images/d11.jpg',
      price: 100,
      countInStock: 19,
      brand: 'Spartan',
      rating: 3,
      numReviews: 10,
      description: 'High quality cricket bat',
    },
    {
      _id: '12',
      name: 'SS TON Cricket Bat',
      catergory: 'Cricker Bats',
      image: '/images/d12.jpg',
      price: 150,
      countInStock: 14,
      brand: 'SS TON ',
      rating: 3.5,
      numReviews: 12,
      description: 'High quality cricket bat',
    },
  ],
}
export default data
